[package]
name = "trin"
version = "0.1.0"
authors = ["Jacob Kaufmann <jacobkaufmann18@gmail.com>", "Jason Carver <ut96caarrs@snkmail.com>"]
edition = "2021"
rust-version = "1.58.0"
default-run = "trin"
repository = "https://github.com/ethereum/trin"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
discv5 = { git = "https://github.com/sigp/discv5.git", branch = "master" }
ethereum-types = "0.12.1"
hex = "0.4.3"
log = "0.4.17"
prometheus_exporter = "0.8.4"
rand = "0.8.4"
rlp = "0.5.0"
serde_json = "1.0.59"
sha3 = "0.9.1"
structopt = "0.3"
tokio = { version = "1.8.0", features = ["full"] }
tracing = "0.1.26"
tracing-subscriber = "0.2.18"
trin-core = { path = "trin-core" }
trin-history = { path = "trin-history" }
trin-state = { path = "trin-state" }

[dev-dependencies]
ethportal-peertest = { path = "ethportal-peertest" }
env_logger = "0.8.2"
test-log = { version = "0.2.10", features = ["trace"] }
tracing-subscriber = "0.2.18"

[workspace]
members = [
    "trin-history",
    "trin-state",
    "trin-core",
    "trin-cli",
    "ethportal-peertest",
    "utp-testing",
]
